name: paged_datatable_example
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  paged_datatable:
    path: ../
  faker: any
  darq: any
  intl: any
  equatable: any
  google_fonts: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
